curl -v http://localhost:8090/simpleProcess & 
curl -v http://localhost:8090/simpleProcess &
curl -v http://localhost:8090/simpleProcess &
curl -v http://localhost:8090/simpleProcess &
curl -v http://localhost:8090/simpleProcess &
curl -v http://localhost:8090/simpleProcess &
curl -v http://localhost:8090/simpleProcess &
curl -v http://localhost:8090/simpleProcess &
curl -v http://localhost:8090/simpleProcess &
curl -v http://localhost:8090/simpleProcess &